algoritmo "semnome"
// Função :
// Autor :
// Data : 09/03/2020
// Seção de Declarações 
var
     nota1, nota2, nota3, media: real
inicio
// Seção de Comandos 
escreva ("Qual a sua primeira nota")
leia (nota1)
escreva ("qual a sua segunda nota")
leia (nota2)
escreva ("qua a sua terceira nota")
leia (nota3)

media <- (nota1 + nota2 + nota3) / 3
escreva ("A sua média é ", media)
fimalgoritmo
