algoritmo "semnome"
// Função :
// Autor :
// Data : 09/03/2020
// Seção de Declarações 
var
cubo,raizqu,quadrado, raizc, valor:real
inicio
// Seção de Comandos
escreva ("Qual é o valor")
leia (valor)

cubo<- valor ^ 3
raizqu <- raizq(valor)
quadrado <- valor ^ 2
raizc <- valor ^(1/3)

escreva("O cubo é: ", cubo, ", a raíz quadrada é: ", raizqu, ", o quadrado é: ", quadrado, ", a raiz cúbica é: ", raizc)
fimalgoritmo
